name: Test
on: [push, pull_request]
jobs:
  test-vers:
    strategy:
      matrix:
        node: ['8.6.0', '8', '10', '12', '14']
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node }}
    - run: npm install
    - run: npm test
